autoholds/urls.py
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.


"""autoholds URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""

from django.conf.urls import include, url
from django.contrib import admin
from patron import views as patron_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^patron/', include('patron.urls')),
    url(r'^$', patron_views.redirect_to_login),
]

patron/urls.py
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls import url

from . import views

app_name = 'patron'

urlpatterns = [
    url(r'login$', views.login, name='login'),
    url(r'logout$', views.logout, name='logout'),
    url(r'add_registration$', views.add_registration, name='add_registration'),
    url(r'change_default_format$', views.change_default_format, name='change_default_format'),
    url(r'change_default_language$', views.change_default_language, name='change_default_language'),
    url(r'change_pickup_location$', views.change_pickup_location, name='change_pickup_location'),
    url(r'remove_registration$', views.remove_registration, name='remove_registration'),
    url(r'$', views.account, name='account'),
]

patron/models.py
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.db import models
from django.db.models.expressions import RawSQL


class Author(models.Model):
    name = models.CharField(max_length=255, unique=True)
    friendly_name = models.CharField(max_length=255)
    note = models.TextField(null=True, blank=True)
    patrons = models.ManyToManyField('Patron', through='Registration')

    def __str__(self):
        return self.name


class Format(models.Model):
    code = models.CharField(max_length=1)
    value = models.CharField(max_length=255)
    active = models.BooleanField(default=True)

    @staticmethod
    def default():
        return Format.objects.filter(code=settings.PATRON_DEFAULT_FORMAT).first()

    def __str__(self):
        return self.value


class Language(models.Model):
    code = models.CharField(max_length=3, unique=True)
    name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)

    @staticmethod
    def default():
        return Language.objects.filter(code=settings.PATRON_DEFAULT_LANGUAGE).first()

    def __str__(self):
        return self.code


class PickupLocation(models.Model):
    code = models.CharField(max_length=5, unique=True)
    name = models.CharField(max_length=255)
    active = models.BooleanField(default=True)

    @staticmethod
    def default():
        return PickupLocation.objects.filter(code=settings.PATRON_DEFAULT_PICKUP_LOCATION).first()

    def __str__(self):
        return self.code


class Patron(models.Model):
    patron_record_number = models.IntegerField(unique=True)
    pickup_location = models.ForeignKey(PickupLocation, models.PROTECT)
    default_format = models.ForeignKey(Format, models.PROTECT)
    default_language = models.ForeignKey(Language, models.PROTECT)
    note = models.TextField(null=True, blank=True)
    authors = models.ManyToManyField('Author', through='Registration')

    @staticmethod
    def for_sierra_patron(sierra_patron):
        patron_record_number = sierra_patron['id']
        patron = Patron.objects.filter(patron_record_number=patron_record_number).first()
        if not patron:
            home_library_code = sierra_patron['fixedFields']['53']['value'].strip()
            pickup_location = PickupLocation.objects.filter(code=home_library_code).first()
            if not pickup_location:
                pickup_location = PickupLocation.default()
            default_format = Format.default()
            pref_language_code = sierra_patron['fixedFields']['263']['value'].strip()
            default_language = Language.objects.filter(code=pref_language_code).first()
            if not default_language:
                default_language = Language.default()
            patron = Patron(
                patron_record_number=patron_record_number,
                pickup_location=pickup_location,
                default_format=default_format,
                default_language=default_language
            )
            patron.save()
        return patron

    def __str__(self):
        return ".p{}a".format(self.patron_record_number)


class Registration(models.Model):
    patron = models.ForeignKey(Patron, models.CASCADE)
    author = models.ForeignKey(Author, models.CASCADE)
    format = models.ForeignKey(Format, models.PROTECT)
    language = models.ForeignKey(Language, models.PROTECT)
    hold_queue_order = models.IntegerField()

    def __str__(self):
        return 'Patron .p{}a for author {}, format {}, language {}, queue pos {}'.format(
            self.patron.patron_record_number,
            self.author.name,
            self.format.code,
            self.language.code,
            self.hold_queue_order
        )

    def move_to_last_in_hold_queue_order(self):
        self.hold_queue_order = RawSQL(
            'SELECT hold_queue_order + 1 '
            'FROM patron_registration '
            'WHERE author_id = %s AND format_id = %s AND language_id = %s '
            'ORDER BY hold_queue_order DESC '
            'LIMIT 1',
            (self.author_id, self.format_id, self.language_id)
        )
        self.save()
        self.refresh_from_db()

patron/views.py
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.


from django.conf import settings
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.views.decorators.http import require_http_methods

from patron.models import Author, Format, Language, Patron, PickupLocation, Registration
from sierra.api import SierraApi_v2


def account(request):
    patron = _patron_in_session(request)
    registrations = patron.registration_set.order_by('author__friendly_name', 'format__value', 'language__name')
    return render(
        request, 'patron/account.html',
        context={
            'authors': Author.objects.all().order_by('friendly_name'),
            'formats': Format.objects.filter(active=True).order_by('value'),
            'languages': Language.objects.filter(active=True).order_by('name'),
            'patron': patron,
            'patron_name': _patron_name_in_session(request),
            'pickup_locations': PickupLocation.objects.filter(active=True).order_by('name'),
            'registrations': registrations,
        }
    )


def add_registration(request):
    author_id = int(request.POST['author'])
    format_id = int(request.POST['format'])
    language_id = int(request.POST['language'])
    if author_id == 0:
        messages.info(request, 'Select an author before you try to add an auto-hold.')
    else:
        patron_obj = _patron_in_session(request)
        author_obj = Author.objects.get(pk=author_id)
        format_obj = Format.objects.get(pk=format_id)
        language_obj = Language.objects.get(pk=language_id)
        reg = Registration(
                patron=patron_obj,
                author=author_obj,
                format=format_obj,
                language=language_obj,
                hold_queue_order=1
            )
        reg.save()
        reg.move_to_last_in_hold_queue_order()
        messages.success(request, 'We successfully added the auto-hold.')
    return HttpResponseRedirect(reverse('patron:account'))


@require_http_methods(['POST'])
def change_default_format(request):
    id_param = request.POST['id']
    new_format = Format.objects.get(pk=id_param)
    patron = _patron_in_session(request)
    patron.default_format = new_format
    patron.save()
    return JsonResponse({'ok': True})


@require_http_methods(['POST'])
def change_default_language(request):
    id_param = request.POST['id']
    new_language = Language.objects.get(pk=id_param)
    patron = _patron_in_session(request)
    patron.default_language = new_language
    patron.save()
    return JsonResponse({'ok': True})


@require_http_methods(['POST'])
def change_pickup_location(request):
    id_param = request.POST['id']
    pickup_location = PickupLocation.objects.get(pk=id_param)
    patron = _patron_in_session(request)
    patron.pickup_location = pickup_location
    patron.save()
    return JsonResponse({'ok': True})


def login(request):
    try:
        barcode = request.POST['barcode']
    except KeyError:
        return render(request, 'patron/login.html')
    barcode = barcode.strip()
    if not barcode:
        messages.info(request, 'Enter your barcode before trying to log in.')
        return render(request, 'patron/login.html')
    sierra_api = _sierra_api_in_session(request)
    sierra_patron = sierra_api.patrons_find(barcode, fields='id,names,fixedFields')
    if not sierra_patron:
        messages.info(request, 'The barcode you entered seems to be incorrect.')
        return render(request, 'patron/login.html')
    autoholds_patron = Patron.for_sierra_patron(sierra_patron)
    request.session['patron_id'] = autoholds_patron.id
    request.session['patron_name'] = sierra_patron['names'][0]
    messages.info(request, 'You successfully logged in.')
    return HttpResponseRedirect(reverse('patron:account'))


def logout(request):
    request.session.clear()
    return HttpResponseRedirect(reverse('patron:login'))


def redirect_to_login(request):
    return HttpResponseRedirect(reverse('patron:login'))


def remove_registration(request):
    reg_id = request.POST['id']
    reg = Registration.objects.get(pk=reg_id)
    reg.delete()
    messages.success(request, 'We successfully removed the auto-hold.')
    return HttpResponseRedirect(reverse('patron:account'))


def _sierra_api_in_session(request):
    try:
        access_token = request.session['sierra_api_access_token']
        return SierraApi_v2.attach(settings.SIERRA_API.base_url, access_token)
    except KeyError:
        sierra_api = SierraApi_v2.login(
            settings.SIERRA_API.base_url,
            settings.SIERRA_API.client_key,
            settings.SIERRA_API.client_secret
        )
        request.session['sierra_api_access_token'] = sierra_api.access_token
        return sierra_api


def _patron_in_session(request):
    return Patron.objects.get(pk=request.session['patron_id'])


def _patron_name_in_session(request):
    try:
        return request.session['patron_name']
    except KeyError:
        return 'Sir/Madam'

patron/templates/patron/account.html
{% extends 'patron/base.html' %}

{% comment "Copyright notice" %}
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% load staticfiles %}

{% block panel-heading %}{{ patron_name }}{% endblock %}

{% block panel-body %}
<div class="container-fluid">
    <div class="row form">
        <div class="col-sm-4">
            <div class="form-group">
                <label for="pickup-location">
                    Pickup Location
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true" data-help-for="pickup-location"></span>
                </label>
                <select id="pickup-location" class="form-control"
                        data-toggle="tooltip" data-placement="bottom"
                        title="Change where you want to pickup the holds we place for you. Note this only changes new holds, not existing holds.">
                    {% for x in pickup_locations %}
                        {% if x == patron.pickup_location %}
                            <option value="{{ x.id }}" selected>{{ x.name }}</option>
                        {% else %}
                            <option value="{{ x.id }}">{{ x.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>

            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label for="default-format">
                    Preferred Format
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true" data-help-for="default-format"></span>
                </label>
                <select id="default-format" class="form-control"
                        data-toggle="tooltip" data-placement="bottom"
                        title="Choose which format you prefer the most">
                    {% for x in formats %}
                        {% if x == patron.default_format %}
                            <option value="{{ x.id }}" selected>{{ x.value }}</option>
                        {% else %}
                            <option value="{{ x.id }}">{{ x.value }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="form-group">
                <label for="default-language">
                    Preferred Language
                    <span class="glyphicon glyphicon-question-sign" aria-hidden="true" data-help-for="default-language"></span>
                </label>
                <select id="default-language" class="form-control"
                        data-toggle="tooltip" data-placement="bottom"
                        title="Choose the language you prefer to read in the most">
                    {% for x in languages %}
                        {% if x == patron.default_language %}
                            <option value="{{ x.id }}" selected>{{ x.name }}</option>
                        {% else %}
                            <option value="{{ x.id }}">{{ x.name }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Author</th>
                        <th>Format</th>
                        <th>Language</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <form class="form" action="{% url 'patron:add_registration' %}" method="post">
                        <tr class="success">
                            {%  csrf_token %}
                            <td>
                                <select id="add-author" name="author" class="form-control">
                                    <option value="0" selected></option>
                                    {% for x in authors %}
                                        <option value="{{ x.id }}">{{ x.friendly_name }}</option>
                                    {% endfor %}
                                </select>
                            </td>
                            <td>
                                <select id="add-format" name="format" class="form-control">
                                    {% for x in formats %}
                                        {% if x == patron.default_format %}
                                            <option value="{{ x.id }}" selected>{{ x.value }}</option>
                                        {% else %}
                                            <option value="{{ x.id }}">{{ x.value }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </td>
                            <td>
                                <select id="add-language" name="language" class="form-control">
                                    {% for x in languages %}
                                        {% if x == patron.default_language %}
                                            <option value="{{ x.id }}" selected>{{ x.name }}</option>
                                        {% else %}
                                            <option value="{{ x.id }}">{{ x.name }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </td>
                            <td>
                                <button type="submit" id="add-button" class="btn btn-success">
                                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                                </button>
                            </td>
                        </tr>
                    </form>
                    <form id="remove-form" class="form" action="{% url 'patron:remove_registration' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="id" id="remove-form-id">
                        {% for x in registrations %}
                            <tr id="reg-{{ x.id }}">
                                <td>{{ x.author.friendly_name }}</td>
                                <td>{{ x.format.value }}</td>
                                <td>{{ x.language.name }}</td>
                                <td>
                                    <button class="btn btn-danger" data-remove-button="{{ x.id }}">
                                        <span class="glyphicon glyphicon-minus" aria-hidden="true"></span>
                                    </button>
                                </td>
                            </tr>
                        {% endfor %}
                    </form>
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock panel-body %}

{% block scripts-extra %}
    <script src="{% static 'patron/account.js' %}"></script>
    <script>
        $(function () {
            {% for m in messages %}
                {% if m.level == DEFAULT_MESSAGE_LEVELS.INFO %}
                    showToast('info', "{{ m | escapejs }}");
                {% elif m.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    showToast('success', "{{ m | escapejs }}");
                {% elif m.level == DEFAULT_MESSAGE_LEVELS.WARNING %}
                    showToast('warning', "{{ m | escapejs }}");
                {% elif m.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    showToast('error', "{{ m | escapejs }}");
                {% endif %}
            {% endfor %}
        });
    </script>
{% endblock %}

patron/templates/patron/base.html
<!--
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.
-->

{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
{% block head %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Auto-Holds</title>
    <link href="{% static 'common/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'common/jquery-toast-plugin/jquery.toast.min.css' %}" rel="stylesheet">
    <link href="{% static 'patron/style.css'%}" rel="stylesheet">
    {% block head-extra %}{% endblock %}
{% endblock %}
</head>

<body>
{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-md-12">
            <nav class="navbar navbar-default" role="navigation">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                                data-target="#patron-base-navbar-collapse-1" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="#">Auto-Holds</a>
                    </div>
                    <div class="collapse navbar-collapse" id="patron-base-navbar-collapse-1">
                        {% block navbar-logout %}
                            <form class="navbar-form navbar-right" action="{% url 'patron:logout' %}" method="get">
                                <button type="submit" class="btn btn-default">Logout</button>
                            </form>
                        {% endblock %}
                    </div>
                </div>
            </nav>
        </div>
    </div>

    {% block content %}
        {% block pre-panel %}{% endblock %}
        <div class="row">
            <div class="col-md-12">
                <div class="panel panel-primary">
                    <div class="panel-heading">{% block panel-heading %}{% endblock %}</div>
                    <div class="panel-body">{% block panel-body %}{% endblock %}</div>
                </div>
            </div>
        </div>
    {% endblock %}

</div>

{% endblock body %}

{% block scripts %}
    <script src="{% static 'common/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'common/jquery-toast-plugin/jquery.toast.min.js' %}"></script>
    <script src="{% static 'common/bootstrap/js/bootstrap.min.js' %}"></script>
    {% block scripts-extra %}{% endblock %}
{% endblock %}

</body>
</html>

patron/templates/patron/login.html
{% extends 'patron/base.html' %}

{% comment "Copyright notice" %}
# Copyright 2016 Susan Bennett, David Mitchell, Jim Nicholls
#
# This file is part of AutoHolds.
#
# AutoHolds is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AutoHolds is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AutoHolds.  If not, see <http://www.gnu.org/licenses/>.
{% endcomment %}

{% block navbar-logout %}{% endblock %}

{% block pre-panel %}
    {% for m in messages %}
        <div class="row">
            <div class="col-md-12">
                <div class="alert alert-info">{{ m }}</div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block panel-heading %}Enter your barcode to log in{% endblock %}

{% block panel-body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form class="form-inline" action="{% url 'patron:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="barcode">Barcode</label>
                    <input type="password" name="barcode" id="barcode">
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock panel-body %}